CREATE TABLE ORDER_DETAILS (
    OrderDetailID NUMBER PRIMARY KEY,
    OrderID NUMBER,
    ProdID NUMBER,
    Quantity NUMBER NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
    CONSTRAINT fk_product FOREIGN KEY (ProdID) REFERENCES PRODUCT(ProdID)
);
ALTER TABLE ORDERS
ADD OrderDate DATE DEFAULT SYSDATE;
